/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ZonasRouteImport } from './routes/zonas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonasRoute = ZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades': typeof PropiedadesRoute
  '/servicios': typeof ServiciosRoute
  '/zonas': typeof ZonasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades': typeof PropiedadesRoute
  '/servicios': typeof ServiciosRoute
  '/zonas': typeof ZonasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades': typeof PropiedadesRoute
  '/servicios': typeof ServiciosRoute
  '/zonas': typeof ZonasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nosotros' | '/propiedades' | '/servicios' | '/zonas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nosotros' | '/propiedades' | '/servicios' | '/zonas'
  id: '__root__' | '/' | '/nosotros' | '/propiedades' | '/servicios' | '/zonas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NosotrosRoute: typeof NosotrosRoute
  PropiedadesRoute: typeof PropiedadesRoute
  ServiciosRoute: typeof ServiciosRoute
  ZonasRoute: typeof ZonasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zonas': {
      id: '/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof ZonasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NosotrosRoute: NosotrosRoute,
  PropiedadesRoute: PropiedadesRoute,
  ServiciosRoute: ServiciosRoute,
  ZonasRoute: ZonasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
